### PR TITLE
Use email as account name in Vault TOTP; allow setting issuer name in env

### LINKED ISSUE #258: Extremely difficult to understand UID, use email instead
https://github.com/rubykube/barong/blob/b826730091d82e50f75a6415bdf01b925f9c2133/lib/vault/totp.rb#L33

@dkkoval Can you please fix this ?
Also I need ability to specify issuer name with ENV.

### PR DESCRIPTION
**Pull request by gfedorenko**
- Pass email along with uid to vault
- Get issuer from ENV
Closes #258

### CODE REVIEW

**Comment by gfedorenko** [comment]
@dkkoval yes, I tested. 2FA works fine and Google Authenticator shows email and not uid. Seems like I didn’t break it)

**Comment by antonror** [comment]
selection_006

**Comment by gfedorenko** [comment]
Hello @antonror 

You should configure vault. Set up Vaul server and see our 2FA docs.

**Comment by antonror** [comment]
@gfedorenko thank you for such a rapid response!

**Pull request merged**
