### PR TITLE
Make drag and drop for documents work

### PR DESCRIPTION
**Pull request by amir-budaychiev**
Related with issue #125

### CODE REVIEW

**Comment by gfedorenko** [comment]
@amir-budaychiev maybe we can just use ```yarn add dropify```

**Comment by amir-budaychiev** [comment]
@gfedorenko done

**Comment by dutchakdev** [comment]
Have problem after update: 
`Some fields are empty or invalid`

In logs:

```
Started POST "/documents" for 172.17.0.1 at 2018-02-23 16:41:54 +0000
Processing by DocumentsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"...secure...", "document"=>{"upload"=>#<ActionDispatch::Http::UploadedFile:0x00007fef60c20a18 @tempfile=#<Tempfile:/tmp/RackMultipart20180223-1-1fkpf2f.jpg>, @original_filename="97d2d4a9290283a4942ebea4938fe96123d7df13_full.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"document[upload]\"; filename=\"97d2d4a9290283a4942ebea4938fe96123d7df13_full.jpg\"\r\nContent-Type: image/jpeg\r\n">, "doc_type"=>"Passport", "doc_expire"=>"2018-02-15", "doc_number"=>"EX033030"}, "commit"=>"Submit"}
  Account Load (0.4ms)  SELECT  `accounts`.* FROM `accounts` WHERE `accounts`.`id` = 5 ORDER BY `accounts`.`id` ASC LIMIT 1
  Profile Load (0.4ms)  SELECT  `profiles`.* FROM `profiles` WHERE `profiles`.`account_id` = 5 LIMIT 1
   (0.3ms)  BEGIN
  Profile Load (0.3ms)  SELECT  `profiles`.* FROM `profiles` WHERE `profiles`.`id` = 1 LIMIT 1
   (0.5ms)  ROLLBACK
Redirected to http://localhost:3000/documents/new
Completed 302 Found in 13ms (ActiveRecord: 2.0ms)


Started GET "/documents/new" for 172.17.0.1 at 2018-02-23 16:41:54 +0000
Processing by DocumentsController#new as HTML
  Account Load (0.3ms)  SELECT  `accounts`.* FROM `accounts` WHERE `accounts`.`id` = 5 ORDER BY `accounts`.`id` ASC LIMIT 1
  Rendering documents/new.html.erb within layouts/application
  Rendered documents/_form.html.erb (2.0ms)
  Rendered documents/new.html.erb within layouts/application (3.0ms)
  Website Load (0.4ms)  SELECT  `websites`.* FROM `websites` WHERE `websites`.`domain` = 'mac.localhost' LIMIT 1
  CACHE Website Load (0.0ms)  SELECT  `websites`.* FROM `websites` WHERE `websites`.`domain` = 'mac.localhost' LIMIT 1  [["domain", "mac.localhost"], ["LIMIT", 1]]
  CACHE Website Load (0.0ms)  SELECT  `websites`.* FROM `websites` WHERE `websites`.`domain` = 'mac.localhost' LIMIT 1  [["domain", "mac.localhost"], ["LIMIT", 1]]
  Profile Load (0.4ms)  SELECT  `profiles`.* FROM `profiles` WHERE `profiles`.`account_id` = 5 LIMIT 1
  Rendered layouts/shared/_account_footer.html.erb (2.9ms)
  CACHE Website Load (0.0ms)  SELECT  `websites`.* FROM `websites` WHERE `websites`.`domain` = 'mac.localhost' LIMIT 1  [["domain", "mac.localhost"], ["LIMIT", 1]]
Completed 200 OK in 17ms (Views: 12.8ms | ActiveRecord: 1.2ms)

```

**Comment by gfedorenko** [comment]
@dutchakdev Hi)
The file size should be from 180kb to 10mb. Check if the file fits minimum requirement

**Comment by dutchakdev** [comment]
@gfedorenko 
size is 24 kb

**Comment by gfedorenko** [comment]
@dutchakdev yeah, so that's the problem. Just set minimum size of the upload to 0 or upload bigger file

**Pull request merged**
